import Image from "next/image";
import Link from "next/link";
import SiteChrome from "../components/site-chrome";

const pages: Record<string, { eyebrow: string; title: string; text: string; label: string; features: string[] }> = {
  "online-classes": { eyebrow: "Survive Morocco", title: "Darija classes for real life", text: "Build useful Moroccan Arabic with clear lessons, friendly practice, and conversations you can use the same week.", label: "A practical path", features: ["Small groups capped at 8 learners", "Weekly speaking practice with a native teacher", "A personal phrasebook for your Morocco"] },
  "atay-club": { eyebrow: "Survive Morocco", title: "Come sit for the Atay Club", text: "A relaxed weekly gathering to practice Darija, meet other learners, and keep your progress moving.", label: "Every Thursday", features: ["60 minutes of low-pressure conversation", "Fresh prompts about life in Morocco", "Replay and phrase notes after every session"] },
  workshops: { eyebrow: "Experience Morocco", title: "Learn by doing", text: "Join practical workshops where language and Moroccan culture make sense together.", label: "Hands-on learning", features: ["Cook a dish from start to finish", "Learn the words people actually use", "Leave with recipes, phrases, and new friends"] },
  activities: { eyebrow: "Experience Morocco", title: "Make Morocco your classroom", text: "Practice everyday Darija through thoughtful activities, good food, and time spent with local people.", label: "Out in the city", features: ["Small, local experiences in Marrakech", "Useful language for everyday moments", "A welcoming group for every level"] },
  trips: { eyebrow: "Experience Morocco", title: "Take Darija on the road", text: "Explore Morocco with a small group, welcoming hosts, and plenty of reasons to use what you learn.", label: "Seasonal journeys", features: ["Two days with a group of curious learners", "Local hosts, villages, and shared meals", "Travel support from first question to last tea"] },
  community: { eyebrow: "Community", title: "Find your people", text: "Meet learners from around the world, join the conversation, and keep Darija part of your week.", label: "A place to belong", features: ["A friendly group chat that stays useful", "Weekly prompts to keep you speaking", "Meetups online and in Marrakech"] },
  "whats-on": { eyebrow: "What’s on", title: "Make a date with Morocco", text: "Browse upcoming Atay Club sessions, workshops, trips, and community gatherings.", label: "The September calendar", features: ["Atay Club: Thursday tea & talk · Sep 04", "Tagine cooking workshop · Sep 13", "Atlas villages weekend · Sep 27"] },
  pricing: { eyebrow: "The atay ritual", title: "Choose your way to learn", text: "Start with drop-in classes, build a rhythm with a monthly subscription, or go all in with full immersion.", label: "Three ways to begin", features: ["First glass: flexible drop-in classes", "Second glass: a steady monthly rhythm", "Third glass: classes, trips, and workshops"] },
  "start-learning": { eyebrow: "Yallah", title: "Your first Darija class starts here", text: "Book a free trial class and find a learning rhythm that feels useful, social, and distinctly Moroccan.", label: "One good first step", features: ["Tell us what you want to do in Morocco", "Meet Ahmed for a relaxed 20-minute chat", "Leave with a clear recommendation"] },
};

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const page = pages[slug] ?? pages["start-learning"];

  if (slug === "about-me") return <SiteChrome><main className="full-page about-page"><section className="about-hero wrap"><div><div className="eyebrow">About me · Marrakech</div><h1>Language is a door. I’m here to help you open it.</h1><p className="page-intro">I teach the Darija people speak when the textbook is closed: warm, quick, imperfect, and full of life.</p><Link className="button button-primary" href="/start-learning">Meet me in a free class</Link></div><div className="about-portrait"><Image src="/ahmed.png" alt="Ahmed, your Darija teacher" fill sizes="(max-width: 800px) 100vw, 45vw" /><span>أهلا وسهلا</span></div></section><section className="about-story"><div className="wrap story-grid"><div className="section-head"><div className="eyebrow">The short version</div><h2>Darija lives between the lines.</h2></div><div><p>I’m Ahmed, born and raised in Morocco. For years, I watched smart, motivated people learn formal Arabic and then freeze when a taxi driver greeted them in Darija.</p><p>So I built the kind of learning space I wished they had: practical lessons, real cultural context, and enough room to make mistakes out loud.</p><p>Whether you’re visiting for two weeks, building a life here, or simply curious about the language, we’ll start with the moments you actually want to have.</p></div></div></section><section className="section wrap"><div className="section-head centered"><div className="eyebrow">How I teach</div><h2>Useful first. Human always.</h2></div><div className="principles"><article><strong>01</strong><h3>Start with your life</h3><p>Your goals decide the vocabulary. We build from the conversations you want to join.</p></article><article><strong>02</strong><h3>Say it out loud</h3><p>Confidence comes from trying, listening, and trying again in a room that feels kind.</p></article><article><strong>03</strong><h3>Put it somewhere real</h3><p>Tea, markets, kitchens, and mountain roads give new words somewhere to live.</p></article></div></section><section className="about-signoff wrap"><div><div className="eyebrow">Come as you are</div><h2>You don’t need to be “good at languages.” You just need a reason to say marhaba.</h2></div><Link className="button button-dark" href="/contact-me">Start a conversation</Link></section></main></SiteChrome>;

  if (slug === "contact-me") return <SiteChrome><main className="full-page contact-page"><section className="contact-hero wrap"><div><div className="eyebrow">Contact me · مرحبا</div><h1>Bring me your questions, plans, and slightly messy Darija.</h1><p className="page-intro">Tell me what you’re hoping to do with Moroccan Arabic. I’ll point you toward the right class, club, or first step.</p><div className="contact-details"><a href="mailto:hello@darijawithahmed.com"><small>Email</small>hello@darijawithahmed.com</a><a href="https://instagram.com" target="_blank" rel="noreferrer"><small>Social</small>@darijawithahmed</a><div><small>Based in</small>Marrakech, Morocco</div></div></div><form className="contact-form" action="mailto:hello@darijawithahmed.com" method="post" encType="text/plain"><div className="form-heading"><span>01</span><h2>Let’s make a plan</h2></div><label>Name<input name="name" placeholder="Your name" required /></label><label>Email<input type="email" name="email" placeholder="you@example.com" required /></label><label>What brings you here?<select name="interest" defaultValue=""><option value="" disabled>Select one</option><option>Online classes</option><option>Atay Club</option><option>A trip or workshop</option><option>I’m not sure yet</option></select></label><label>Message<textarea name="message" placeholder="Tell me a little about your goals..." rows={5} required /></label><button className="button button-primary" type="submit">Send my note <span>→</span></button><small className="form-note">I usually reply within two working days.</small></form></section><section className="contact-strip"><div className="wrap contact-strip-inner"><div><span className="strip-mark">✦</span><h2>Not ready to write?</h2><p>Start with a free 20-minute trial class and see if the rhythm feels right.</p></div><Link className="button button-light" href="/start-learning">Book a free trial</Link></div></section></main></SiteChrome>;

  return <SiteChrome><main className="full-page detail-page"><section className="detail-hero wrap"><div className="detail-copy"><div className="eyebrow">{page.eyebrow}</div><h1>{page.title}</h1><p className="page-intro">{page.text}</p><div className="subpage-actions"><Link className="button button-primary" href="/contact-me">Ask Ahmed where to start</Link><Link className="button button-outline" href="/">Explore everything</Link></div></div><div className="detail-note"><span>✦</span><small>{page.label}</small><ul>{page.features.map((feature) => <li key={feature}>{feature}</li>)}</ul></div></section><section className="detail-band"><div className="wrap detail-band-grid"><div><div className="eyebrow">Made for real life</div><h2>Learn the phrase, then go use it.</h2></div><p>Every experience is designed to move you from recognition to participation. You’ll leave with something to say, somewhere to go, and a reason to come back.</p></div></section><section className="section wrap detail-next"><div className="section-head"><div className="eyebrow">Keep exploring</div><h2>There’s always another door in.</h2></div><div className="next-links"><Link href="/online-classes"><span>01</span>Learn with a class <b>→</b></Link><Link href="/community"><span>02</span>Find your people <b>→</b></Link><Link href="/whats-on"><span>03</span>See what’s on <b>→</b></Link></div></section></main></SiteChrome>;
}
